from typing import List

class AssimpExporter:
    def __init__(self, enable_logging: bool = False) -> None: ...
    def get_supported_formats(self) -> List[str]: ...
    def usdz_to_obj(self, usdz_file: str, obj_file: str) -> bool: ...
    def get_last_error(self) -> str: ...
