name: Build Wheels for Release

env:
  UV_SYSTEM_PYTHON: 1

# 创建 Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'  # 推送 tag 时触发 release

jobs:
  build:
    name: python ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        submodules: recursive

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: uv sync

    - name: Build the project
      run: uv build

    - name: Minimize uv cache
      run: uv cache prune --ci

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.python }}
        path: dist/

  release:
    name: Create Release and Upload Assets
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist-all/

    - name: Flatten artifacts
      run: |
        mkdir -p dist/
        find dist-all/ -name "*.whl" -exec cp {} dist/ \;
        find dist-all/ -name "*.tar.gz" -exec cp {} dist/ \;
        ls -la dist/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
